export const NICHES = [
  {
    key: 'textile',
    label: 'Textile / Apparel',
    emoji: '🧵',
    color: 'from-pink-500 to-rose-500',
    bgLight: 'bg-pink-50',
    units: ['Metres', 'KG', 'Rolls', 'Pieces', 'Bundles'],
    hsnPresets: [
      { code: '5208', desc: 'Woven cotton fabric' },
      { code: '5407', desc: 'Woven synthetic fabric' },
      { code: '6109', desc: 'T-shirts, vests' },
      { code: '6203', desc: "Men's suits, trousers" },
    ],
    invoiceTemplate: 'textile',
    customFields: ['Color', 'Design', 'Lot No.', 'Width'],
    terms: { product: 'Fabric', unit: 'Metres', batch: 'Lot No.' },
    description: 'Wholesalers, weavers & apparel manufacturers',
  },
  {
    key: 'pharma',
    label: 'Pharma Distribution',
    emoji: '💊',
    color: 'from-blue-500 to-cyan-500',
    bgLight: 'bg-blue-50',
    units: ['Strips', 'Boxes', 'Vials', 'Bottles', 'Tablets'],
    hsnPresets: [
      { code: '3004', desc: 'Medicaments in dosage form' },
      { code: '3005', desc: 'Wadding, bandages' },
      { code: '3006', desc: 'Pharmaceutical preparations' },
    ],
    invoiceTemplate: 'pharma',
    customFields: ['Batch No.', 'MFG Date', 'Expiry Date', 'Schedule'],
    terms: { product: 'Medicine', unit: 'Strips', batch: 'Batch No.' },
    description: 'Distributors & chemists',
  },
  {
    key: 'steel',
    label: 'Steel / Metal',
    emoji: '⚙️',
    color: 'from-slate-600 to-zinc-700',
    bgLight: 'bg-slate-50',
    units: ['KG', 'Tonnes', 'Pieces', 'Bundles', 'Sheets'],
    hsnPresets: [
      { code: '7208', desc: 'Flat-rolled iron/steel products' },
      { code: '7214', desc: 'Bars and rods' },
      { code: '7304', desc: 'Tubes and pipes' },
    ],
    invoiceTemplate: 'standard',
    customFields: ['Grade', 'Size', 'Heat No.', 'Thickness'],
    terms: { product: 'Material', unit: 'KG', batch: 'Heat No.' },
    description: 'Steel traders & fabricators',
  },
  {
    key: 'electrical',
    label: 'Electrical Goods',
    emoji: '🔌',
    color: 'from-yellow-500 to-amber-500',
    bgLight: 'bg-yellow-50',
    units: ['Pieces', 'Boxes', 'Rolls', 'Packets', 'Sets'],
    hsnPresets: [
      { code: '8536', desc: 'Electrical apparatus for switching' },
      { code: '8544', desc: 'Insulated wire and cables' },
      { code: '9405', desc: 'Lamps and lighting fittings' },
    ],
    invoiceTemplate: 'standard',
    customFields: ['Wattage', 'Voltage', 'Brand', 'Model No.'],
    terms: { product: 'Product', unit: 'Pieces', batch: 'Serial No.' },
    description: 'Electrical wholesale & retail',
  },
  {
    key: 'agri',
    label: 'Agri / FMCG',
    emoji: '🌾',
    color: 'from-green-500 to-emerald-600',
    bgLight: 'bg-green-50',
    units: ['KG', 'Quintals', 'Bags', 'Litres', 'Tonnes'],
    hsnPresets: [
      { code: '1001', desc: 'Wheat and meslin' },
      { code: '1006', desc: 'Rice' },
      { code: '2101', desc: 'Coffee, tea, maté' },
    ],
    invoiceTemplate: 'standard',
    customFields: ['Crop Year', 'Variety', 'Quality Grade', 'Moisture %'],
    terms: { product: 'Commodity', unit: 'KG', batch: 'Lot No.' },
    description: 'Agri traders & FMCG distributors',
  },
  {
    key: 'construction',
    label: 'Construction / Building',
    emoji: '🏗️',
    color: 'from-orange-500 to-amber-600',
    bgLight: 'bg-orange-50',
    units: ['Pieces', 'Bags', 'Sq. Ft.', 'Tonnes', 'Bundles'],
    hsnPresets: [
      { code: '2523', desc: 'Portland cement' },
      { code: '6810', desc: 'Articles of cement, concrete' },
      { code: '7308', desc: 'Structures of iron or steel' },
    ],
    invoiceTemplate: 'standard',
    customFields: ['Grade', 'Size', 'Brand', 'IS Standard'],
    terms: { product: 'Material', unit: 'Pieces', batch: 'Batch No.' },
    description: 'Builders & construction suppliers',
  },
  {
    key: 'autoparts',
    label: 'Auto Parts',
    emoji: '🚗',
    color: 'from-red-500 to-rose-600',
    bgLight: 'bg-red-50',
    units: ['Pieces', 'Sets', 'Pairs', 'Kits', 'Boxes'],
    hsnPresets: [
      { code: '8708', desc: 'Parts and accessories of motor vehicles' },
      { code: '4011', desc: 'New pneumatic tyres of rubber' },
    ],
    invoiceTemplate: 'standard',
    customFields: ['Part No.', 'Brand', 'Vehicle Model', 'OEM/Aftermarket'],
    terms: { product: 'Part', unit: 'Pieces', batch: 'Part No.' },
    description: 'Auto parts dealers',
  },
  {
    key: 'retail',
    label: 'General Retail',
    emoji: '🛒',
    color: 'from-violet-500 to-purple-600',
    bgLight: 'bg-violet-50',
    units: ['Pieces', 'Boxes', 'Packets', 'Dozens', 'Units'],
    hsnPresets: [
      { code: '9999', desc: 'General goods' },
    ],
    invoiceTemplate: 'standard',
    customFields: ['SKU', 'Brand', 'Category'],
    terms: { product: 'Product', unit: 'Units', batch: 'SKU' },
    description: 'General retail & wholesale',
  },
]

export function getNicheConfig(nicheKey: string) {
  return NICHES.find(n => n.key === nicheKey) || NICHES[NICHES.length - 1]
}

export type NicheConfig = typeof NICHES[0]
